# Generated by Django 3.2.19 on 2023-05-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='博文标题', max_length=512, verbose_name='博文标题')),
                ('blog_from', models.CharField(choices=[('local', '本地编辑'), ('internet', '网络下载')], help_text='博客来源：本地/网络', max_length=255, verbose_name='来源')),
                ('categories', models.CharField(help_text='博文分类id，填写分类id，多个id以英文逗号隔开', max_length=255, verbose_name='分类')),
                ('tags', models.CharField(help_text='博文标签id，填写标签id，多个id以英文逗号隔开', max_length=255, verbose_name='标签')),
                ('content_id', models.CharField(help_text='博文内容id：BlogContentID或者BlogDownloadContentID', max_length=255, verbose_name='博文内容id')),
                ('create_time', models.CharField(blank=True, max_length=255, verbose_name='添加时间')),
                ('update_time', models.CharField(blank=True, max_length=255, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='博文内容，html内容格式', verbose_name='博文内容')),
                ('create_time', models.CharField(blank=True, max_length=255, verbose_name='添加时间')),
                ('update_time', models.CharField(blank=True, max_length=255, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '本地编写博文内容',
                'verbose_name_plural': '本地编写博文内容',
                'db_table': 'blog_content',
            },
        ),
        migrations.CreateModel(
            name='BlogDownloadContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_site', models.CharField(choices=[('csdn', 'csdn')], help_text='原始网站，比如csdn，博客园等描述', max_length=255, verbose_name='原始站点')),
                ('source_url', models.TextField(help_text='原始url地址', verbose_name='原始url地址')),
                ('local_path', models.TextField(blank=True, help_text='从网络下载的博文存放在本机的文件地址', null=True, verbose_name='博文本地地址')),
                ('create_time', models.CharField(blank=True, max_length=255, verbose_name='添加时间')),
                ('update_time', models.CharField(blank=True, max_length=255, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网络下载博文内容',
                'verbose_name_plural': '网络下载博文内容',
                'db_table': 'blog_download_content',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='分类', max_length=255, verbose_name='分类')),
                ('create_time', models.CharField(blank=True, max_length=255, verbose_name='添加时间')),
                ('update_time', models.CharField(blank=True, max_length=255, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='标签', max_length=255, verbose_name='标签')),
                ('create_time', models.CharField(blank=True, max_length=255, verbose_name='添加时间')),
                ('update_time', models.CharField(blank=True, max_length=255, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'blog_tag',
            },
        ),
    ]
