# Generated by Django 3.2.19 on 2023-06-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='', help_text='博文简要描述', max_length=512, verbose_name='博文简要描述'),
            preserve_default=False,
        ),
    ]
