# Generated by Django 3.2.19 on 2023-06-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230601_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.CharField(help_text='博文分类id，填写分类id，只能属于一个分类，不可多对多', max_length=255, verbose_name='分类'),
        ),
    ]
